### ISSUE TITLE
New look.

### ISSUE THREAD

**Issue by devdot4** [horatiorosa/portfolio#2]
This portfolio needs an update asap. Last commit was made 3 years ago. Please make it look hip and cool.

**Comment by horatiorosa** [comment]
thank you for opening this issue. it seems I must have missed this. my pardon for taking so long to address this.

**Comment by devdot4** [comment]
it's alright

**Comment by horatiorosa** [comment]
LOL. I started a new position and my free time was eliminated. I do mention it's a work in progress.
